# Generated by Django 3.0.2 on 2020-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Restaurant name')),
                ('owner_comment', models.TextField()),
                ('payment_method', models.CharField(choices=[('here', 'here'), ('there', 'there')], default='', max_length=30)),
                ('delivery_cost', models.IntegerField(default=0)),
                ('minimum_amount', models.IntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('photo', models.ImageField(upload_to='restaurant_photos', verbose_name='Restaurant photo')),
                ('group', models.ManyToManyField(to='groups.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
