# Generated by Django 3.0.2 on 2020-01-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payment_method',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.PaymentMethod'),
        ),
    ]
