# Generated by Django 3.0.2 on 2020-01-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20200120_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='payment_method',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.PaymentMethod'),
        ),
    ]
