# Generated by Django 3.0.2 on 2020-01-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_detail',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Detail'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Is Owner'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('naver', 'naver'), ('kakao', 'kakao')], default='email', max_length=20, verbose_name='Login Method'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Phone'),
        ),
    ]
