# Generated by Django 3.0.2 on 2020-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20200120_1703'),
        ('users', '0004_auto_20200116_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zzim_list',
            field=models.ManyToManyField(blank=True, related_name='zzims', to='restaurants.Restaurant', verbose_name='찜 리스트'),
        ),
    ]
