# Generated by Django 3.0.2 on 2020-01-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20200116_1702'),
        ('users', '0005_user_zzim_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_list',
            field=models.ManyToManyField(blank=True, related_name='carts', to='menus.Menu', verbose_name='주문표'),
        ),
    ]
