# Generated by Django 3.0.2 on 2020-01-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_cart_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
    ]
