# Generated by Django 3.0.2 on 2020-01-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Menu name')),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='menu_photos', verbose_name='Menu photo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
